* Do we get our morals from religion, or the other way around?

One recurring argument from people of faith has been that religion gives us our morals. That without religion, we would have no foundation upon which to erect a moral code. But is this really what is happening? If we look at our world, our history and ourselves, is this actually the state of affairs that we observe?

In order to discuss these matters in some sort of a rational sense, we need to agree on the definitions of some words. If you look in a dictionary, you will find that the definitions given are of little practical use. Instead I propose to use a set of operational definitions describing these words in terms of how they are actually used by people in discourse. The three words I wish to define and use are morals, religion and spirituality.

Morals are the set of rules which define right from wrong. Our morals tell us that murder is wrong and that helping others is right. An important question to ask is whether these rules change over time, or whether they remain eternally true. Just over the past 100 years our morals have changed to where it is no longer considered immoral to have interracial marriages, and that slavery is no longer appropriate behavior. So no, they do not remain static for all time. They are open to changing.

Religion is the institution wherein a group of people gather together into a community to worship. What and how they worship is being left specifically vague since at this stage it really doesn't matter. What matters is that a religion defines a set of behaviors that those within the group follow. Again, we should look at whether religion changes over time. A cursory look would imply that it doesn't change as most religions have sacred texts that record these religions and freeze them in time. But in practice, they do change. Even Catholicism, arguably the most bureaucratic religion around, changes through devices like papal bulls.

The last term we need is spirituality. Most people view spirituality as the set of techniques that individuals use for self-improvement. Those of faith see this self-improvement as getting closer to their deity. But in general, spirituality is simply the way people become better people, whatever "better" means.

So what is the relationship between these 3 ideas? How do they inform each other? I think that it is relatively clear that all three form a triad of interdependent ideas. A person's morals help define what religious behaviors are OK, and a person's religion help construct their moral code.

Your moral code tells you that slavery is wrong, so even though in the Bible it says that you are allowed to own slaves, most sects of the Christian religion have changed to the point where they say that the behavior of owning slaves is immoral. On the flip side, morals are learned from the behaviors of the adults around you while you are growing up. These behaviors are contrained by the religion that these adults are in. So neither are the sole cause for the other. They work on each other through a feedback mechanism, one directing the other.

As humanists, the biggest problem we have is the behaviors that are allowed, or even encouraged, by some religions. How can we affect change so that these behaviors are curtailed? Since we are not leaders in the religion, we are in no position to effect any changes in the religion from outside. Morals, on the other hand, are affected by a person's environment. If you see someone being an exemplar of moral behavior, you are more likely to be moral. If there is a social pressure towards a particular behavior, you are more likely to see that behavior as moral. Also, if you have been exposed to many different ideas, you are more likely to change your morals based on that exposure.

So does this mean that the agressive tactic favored by Dawkins and Hitchens is the correct one to see change happen? Well, I think that the answer is both yes and no. Yes, it is a valid technique to initiate a change. It forces people to start thinking about their religios behavior and their concept of what is moral. But a catalyst with no fuel leads nowhere. To fuel that reaction, we need to provide examples of moral behavior, provide education of other ways of being. Other possibilities for religious expression.
