* Heavens Above?

If you are reading this letter, you are probably wondering what all of this equipment is for. I probably should have had all of this destroyed, but I just couldn't do it. Especially after realizing what all of this means for all of us. If you are confused, please read on. And I hope that you will do the right thing.

Everything started 11 years ago when I found a long abandoned journal from Tesla's lab. In it, he had described a method of extracting energy from the ambient electromagnetic field of the Earth. Unfortunately, the original design was not very practical since the electromagnetic field gradient near the Earth's surface is not very steep. This means that the machine would need to be massive in order to collect any usable amount of power.

Well, we know something that Tesla didn't. We know that the Van Allen belts exist up there, and that there is an enormous amount of power stored up there. So, taking Tesla's original idea, we simply placed it into orbit to take advantage of this terrific source of stored energy. And it worked beautifully. We could provide more energy then could possibly be used. If only we had left it at that, I would at least be able to sleep at night.

When we were doing our initial tests, we found something very curious. In the seemingly random noise in the plasma, we noticed that there was some kind of organization. There were some very complex patterns that seemed self-organizing. They seemed to stay coherent, at least until we passed them through the power conditioning phase of the equipment.

The very odd characteristics of these patterns piqued my interest. I felt driven to try and find out their source. To that end, I started a search through every scientific and engineering database I could find, trying to find some mention of a similar phenomenon. I had no luck in any of the engineering disciplines, and physics and chemistry likewise came up empty. It wasn't until I extended my search out to biology and psychology that I started to come up with some matches.

The latest high resolution electromagnetic scans of the brain had begun to show that what we call consciousness is actually a self-organizing pattern in the electrical signals travelling around the neurons. The actual synaptic links between neurons were simply the circuit through which these patterns propogated. It was fascinating work. Obviously we had found a natural phenomenon that mimiced this same behavior. I began a collaboration with the leading neuro-psychologists to see how they analyzed these patterns. It turns out that there were some common structures within the patterns that showed up in most scans. These seemed to be structures which represented individual thoughts, words or images. Using their techniques, we began analyzing the patterns we were finding in the plasmas in the Van Allen belts. I don't know if I really thought about what I might find.

The following year, there was a breakthrough. The neuro-psychologists had found a way of mapping these sub-patterns into words. For the first time we were able to effectively read a person's mind. My collaborator sent me a copy of the software that did the translation step and, God only knows what possessed me, I ran the plasma patterns through the program. It seemed to be a random sampling of words. The most common were words like pain, horror, agony, help. At least they seemed random.

The following week, my collaborator sent me a note to say that they had just recorded the first person dying with their equipment. He said that the patterns stayed coherent for a significant amount of time after all other signs of life had left the body.
